# Generated by Django 5.0.6 on 2025-02-12 09:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, choices=[('India', 'India'), ('USA', 'USA'), ('UK', 'UK'), ('Australia', 'Australia'), ('Canada', 'Canada'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Japan', 'Japan'), ('China', 'China'), ('Russia', 'Russia'), ('Brazil', 'Brazil'), ('South Africa', 'South Africa'), ('Nigeria', 'Nigeria'), ('Mexico', 'Mexico'), ('Argentina', 'Argentina'), ('Spain', 'Spain'), ('Portugal', 'Portugal'), ('Greece', 'Greece'), ('Sweden', 'Sweden'), ('Norway', 'Norway'), ('Finland', 'Finland'), ('Denmark', 'Denmark'), ('Netherlands', 'Netherlands'), ('Belgium', 'Belgium'), ('Switzerland', 'Switzerland'), ('Austria', 'Austria'), ('Poland', 'Poland'), ('Czech Republic', 'Czech Republic'), ('Turkey', 'Turkey'), ('Ukraine', 'Ukraine'), ('Hungary', 'Hungary'), ('Romania', 'Romania'), ('Bulgaria', 'Bulgaria'), ('Croatia', 'Croatia'), ('Slovenia', 'Slovenia'), ('Slovakia', 'Slovakia'), ('Lithuania', 'Lithuania'), ('Latvia', 'Latvia'), ('Estonia', 'Estonia'), ('Ireland', 'Ireland'), ('Scotland', 'Scotland'), ('Wales', 'Wales'), ('Northern Ireland', 'Northern Ireland'), ('New Zealand', 'New Zealand'), ('Singapore', 'Singapore'), ('Malaysia', 'Malaysia'), ('Thailand', 'Thailand'), ('Indonesia', 'Indonesia'), ('Philippines', 'Philippines'), ('Vietnam', 'Vietnam'), ('South Korea', 'South Korea'), ('North Korea', 'North Korea'), ('Taiwan', 'Taiwan'), ('Hong Kong', 'Hong Kong'), ('Macau', 'Macau'), ('Bangladesh', 'Bangladesh'), ('Pakistan', 'Pakistan'), ('Sri Lanka', 'Sri Lanka'), ('Nepal', 'Nepal'), ('Bhutan', 'Bhutan'), ('Maldives', 'Maldives'), ('Afghanistan', 'Afghanistan'), ('Iran', 'Iran'), ('Iraq', 'Iraq'), ('Syria', 'Syria'), ('Lebanon', 'Lebanon')], default='India', max_length=50, null=True)),
                ('profile_pic', models.JSONField(blank=True, null=True)),
                ('account_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Blocked', 'Blocked')], default='Active', max_length=50, null=True)),
                ('role', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Supplier', 'Supplier'), ('Customer', 'Customer'), ('Staff', 'Staff')], default='Admin', max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('social_media_links', models.JSONField(blank=True, null=True)),
                ('addition_details', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(blank=True, choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Spanish', 'Spanish'), ('French', 'French'), ('German', 'German'), ('Italian', 'Italian'), ('Portuguese', 'Portuguese'), ('Russian', 'Russian'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Arabic', 'Arabic'), ('Turkish', 'Turkish'), ('Dutch', 'Dutch'), ('Polish', 'Polish'), ('Swedish', 'Swedish'), ('Danish', 'Danish'), ('Norwegian', 'Norwegian'), ('Finnish', 'Finnish'), ('Greek', 'Greek'), ('Czech', 'Czech'), ('Hungarian', 'Hungarian'), ('Romanian', 'Romanian'), ('Bulgarian', 'Bulgarian'), ('Croatian', 'Croatian'), ('Slovak', 'Slovak'), ('Slovenian', 'Slovenian'), ('Lithuanian', 'Lithuanian'), ('Latvian', 'Latvian'), ('Estonian', 'Estonian'), ('Ukrainian', 'Ukrainian'), ('Belarusian', 'Belarusian'), ('Serbian', 'Serbian'), ('Macedonian', 'Macedonian'), ('Bosnian', 'Bosnian'), ('Albanian', 'Albanian'), ('Montenegrin', 'Montenegrin'), ('Catalan', 'Catalan'), ('Basque', 'Basque'), ('Galician', 'Galician'), ('Welsh', 'Welsh'), ('Irish', 'Irish'), ('Scots Gaelic', 'Scots Gaelic'), ('Manx', 'Manx'), ('Cornish', 'Cornish'), ('Breton', 'Breton')], default='English', max_length=50, null=True)),
                ('departMent', models.CharField(blank=True, choices=[('IT', 'IT'), ('HR', 'HR'), ('Finance', 'Finance'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Production', 'Production'), ('Quality Control', 'Quality Control'), ('Purchase', 'Purchase'), ('Logistics', 'Logistics'), ('Customer Service', 'Customer Service'), ('R&D', 'R&D'), ('Legal', 'Legal'), ('Admin', 'Admin'), ('Security', 'Security'), ('Housekeeping', 'Housekeeping'), ('Maintenance', 'Maintenance'), ('Engineering', 'Engineering'), ('Design', 'Design'), ('Testing', 'Testing'), ('Training', 'Training'), ('Consulting', 'Consulting'), ('Support', 'Support'), ('Operations', 'Operations'), ('Management', 'Management'), ('Others', 'Others')], max_length=50, null=True)),
                ('designation', models.CharField(blank=True, choices=[('CEO', 'CEO'), ('CFO', 'CFO'), ('CTO', 'CTO'), ('CMO', 'CMO'), ('COO', 'COO'), ('CIO', 'CIO'), ('CISO', 'CISO'), ('CDO', 'CDO'), ('CRO', 'CRO'), ('CSO', 'CSO'), ('CPO', 'CPO'), ('CLO', 'CLO'), ('CBO', 'CBO'), ('CVO', 'CVO'), ('CNO', 'CNO'), ('CQO', 'CQO'), ('CPDO', 'CPDO'), ('CCO', 'CCO'), ('CDO', 'CDO'), ('CLO', 'CLO'), ('CBO', 'CBO'), ('CVO', 'CVO'), ('CNO', 'CNO'), ('CQO', 'CQO'), ('CPDO', 'CPDO'), ('CCO', 'CCO'), ('CDO', 'CDO'), ('CLO', 'CLO'), ('CBO', 'CBO'), ('CVO', 'CVO'), ('CNO', 'CNO'), ('CQO', 'CQO'), ('CPDO', 'CPDO'), ('CCO', 'CCO'), ('CDO', 'CDO'), ('CLO', 'CLO'), ('CBO', 'CBO'), ('CVO', 'CVO'), ('CNO', 'CNO'), ('CQO', 'CQO'), ('CPDO', 'CPDO'), ('CCO', 'CCO'), ('CDO', 'CDO'), ('CLO', 'CLO'), ('CBO', 'CBO'), ('CVO', 'CVO'), ('CNO', 'CNO'), ('CQO', 'CQO'), ('CPDO', 'CPDO'), ('CCO', 'CCO'), ('CDO', 'CDO'), ('CLO', 'CLO'), ('CBO', 'CBO'), ('CVO', 'CVO'), ('CNO', 'CNO'), ('CQO', 'CQO'), ('CPDO', 'CPDO'), ('CCO', 'CCO'), ('CDO', 'CDO'), ('CLO', 'CLO'), ('CBO', 'CBO'), ('CVO', 'CVO'), ('CNO', 'CNO'), ('CQO', 'CQO'), ('CPDO', 'CPDO'), ('CCO', 'CCO'), ('CDO', 'CDO'), ('CLO', 'CLO'), ('CBO', 'CBO'), ('CVO', 'CVO'), ('CNO', 'CNO'), ('CQO', 'CQO'), ('CPDO', 'CPDO'), ('CCO', 'CCO'), ('CDO', 'CDO'), ('CLO', 'CLO'), ('CBO', 'CBO'), ('CVO', 'CVO'), ('CNO', 'CNO'), ('Other', 'Other')], max_length=50, null=True)),
                ('time_zone', models.CharField(blank=True, choices=[('UTC-12:00', 'UTC-12:00'), ('UTC-11:00', 'UTC-11:00'), ('UTC-10:00', 'UTC-10:00'), ('UTC-09:30', 'UTC-09:30'), ('UTC-09:00', 'UTC-09:00'), ('UTC-08:00', 'UTC-08:00'), ('UTC-07:00', 'UTC-07:00'), ('UTC-06:00', 'UTC-06:00'), ('UTC-05:00', 'UTC-05:00'), ('UTC-04:00', 'UTC-04:00'), ('UTC-03:30', 'UTC-03:30'), ('UTC-03:00', 'UTC-03:00'), ('UTC-02:00', 'UTC-02:00'), ('UTC-01:00', 'UTC-01:00'), ('UTC', 'UTC'), ('UTC+01:00', 'UTC+01:00'), ('UTC+02:00', 'UTC+02:00'), ('UTC+03:00', 'UTC+03:00'), ('UTC+03:30', 'UTC+03:30'), ('UTC+04:00', 'UTC+04:00'), ('UTC+04:30', 'UTC+04:30'), ('UTC+05:00', 'UTC+05:00'), ('UTC+05:30', 'UTC+05:30'), ('UTC+05:45', 'UTC+05:45'), ('UTC+06:00', 'UTC+06:00'), ('UTC+06:30', 'UTC+06:30'), ('UTC+07:00', 'UTC+07:00'), ('UTC+08:00', 'UTC+08:00'), ('UTC+08:45', 'UTC+08:45'), ('UTC+09:00', 'UTC+09:00'), ('UTC+09:30', 'UTC+09:30'), ('UTC+10:00', 'UTC+10:00'), ('UTC+10:30', 'UTC+10:30'), ('UTC+11:00', 'UTC+11:00'), ('UTC+12:00', 'UTC+12:00'), ('UTC+12:45', 'UTC+12:45'), ('UTC+13:00', 'UTC+13:00'), ('UTC+14:00', 'UTC+14:00')], default='UTC+05:30', max_length=50, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_device', models.CharField(blank=True, max_length=50, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('INR', 'INR'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('JPY', 'JPY'), ('CNY', 'CNY'), ('RUB', 'RUB'), ('BRL', 'BRL'), ('ZAR', 'ZAR'), ('NGN', 'NGN'), ('MXN', 'MXN'), ('ARS', 'ARS'), ('CHF', 'CHF'), ('SEK', 'SEK'), ('NOK', 'NOK'), ('DKK', 'DKK'), ('PLN', 'PLN'), ('CZK', 'CZK'), ('TRY', 'TRY'), ('UAH', 'UAH'), ('HUF', 'HUF'), ('RON', 'RON'), ('BGN', 'BGN'), ('HRK', 'HRK'), ('SLO', 'SLO'), ('SK', 'SK'), ('LT', 'LT'), ('LV', 'LV'), ('EE', 'EE'), ('IE', 'IE'), ('SC', 'SC'), ('WL', 'WL'), ('NI', 'NI'), ('NZ', 'NZ'), ('SGD', 'SGD'), ('MYR', 'MYR'), ('THB', 'THB'), ('IDR', 'IDR'), ('PHP', 'PHP'), ('VND', 'VND'), ('KRW', 'KRW'), ('KPW', 'KPW'), ('TWD', 'TWD'), ('HKD', 'HKD'), ('MOP', 'MOP'), ('BDT', 'BDT'), ('PKR', 'PKR'), ('LKR', 'LKR'), ('NPR', 'NPR'), ('BTN', 'BTN'), ('MVR', 'MVR'), ('AFN', 'AFN'), ('IRR', 'IRR'), ('IQD', 'IQD'), ('SYP', 'SYP'), ('LBN', 'LBN')], default='INR', max_length=50, null=True)),
                ('domain_name', models.CharField(blank=True, max_length=50, null=True)),
                ('plan_type', models.CharField(blank=True, choices=[('Free', 'Free'), ('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium'), ('Enterprise', 'Enterprise')], default='Free', max_length=50, null=True)),
                ('added_by_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user_id_user', to=settings.AUTH_USER_MODEL)),
                ('domain_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_user', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
