# Generated by Django 5.0.6 on 2025-02-12 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.TextField()),
                ('activity_type', models.CharField(blank=True, max_length=50)),
                ('activity_date', models.DateTimeField(auto_now_add=True)),
                ('activity_ip', models.GenericIPAddressField()),
                ('activity_device', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_activity_log', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activity_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=50, unique=True)),
                ('module_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_menu', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('module_url', models.CharField(blank=True, max_length=50, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('module_description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserServices.modules')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleUrls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserServices.modules')),
            ],
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_permission', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_user_permissions', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserServices.modules')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions_1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserShippingAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address_type', models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Other', 'Other')], max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('country', models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('UK', 'UK'), ('Australia', 'Australia'), ('Canada', 'Canada'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Japan', 'Japan'), ('China', 'China'), ('Russia', 'Russia'), ('Brazil', 'Brazil'), ('South Africa', 'South Africa'), ('Nigeria', 'Nigeria'), ('Mexico', 'Mexico'), ('Argentina', 'Argentina'), ('Spain', 'Spain'), ('Portugal', 'Portugal'), ('Greece', 'Greece'), ('Sweden', 'Sweden'), ('Norway', 'Norway'), ('Finland', 'Finland'), ('Denmark', 'Denmark'), ('Netherlands', 'Netherlands'), ('Belgium', 'Belgium'), ('Switzerland', 'Switzerland'), ('Austria', 'Austria'), ('Poland', 'Poland'), ('Czech Republic', 'Czech Republic'), ('Turkey', 'Turkey'), ('Ukraine', 'Ukraine'), ('Hungary', 'Hungary'), ('Romania', 'Romania'), ('Bulgaria', 'Bulgaria'), ('Croatia', 'Croatia'), ('Slovenia', 'Slovenia'), ('Slovakia', 'Slovakia'), ('Lithuania', 'Lithuania'), ('Latvia', 'Latvia'), ('Estonia', 'Estonia'), ('Ireland', 'Ireland'), ('Scotland', 'Scotland'), ('Wales', 'Wales'), ('Northern Ireland', 'Northern Ireland'), ('New Zealand', 'New Zealand'), ('Singapore', 'Singapore'), ('Malaysia', 'Malaysia'), ('Thailand', 'Thailand'), ('Indonesia', 'Indonesia'), ('Philippines', 'Philippines'), ('Vietnam', 'Vietnam'), ('South Korea', 'South Korea'), ('North Korea', 'North Korea'), ('Taiwan', 'Taiwan'), ('Hong Kong', 'Hong Kong'), ('Macau', 'Macau'), ('Bangladesh', 'Bangladesh'), ('Pakistan', 'Pakistan'), ('Sri Lanka', 'Sri Lanka'), ('Nepal', 'Nepal'), ('Bhutan', 'Bhutan'), ('Maldives', 'Maldives'), ('Afghanistan', 'Afghanistan'), ('Iran', 'Iran'), ('Iraq', 'Iraq'), ('Syria', 'Syria'), ('Lebanon', 'Lebanon')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shipping_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
