# Generated by Django 5.0.6 on 2025-02-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0002_activitylog_modules_moduleurls_userpermissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Supplier', 'Supplier'), ('Customer', 'Customer'), ('Staff', 'Staff'), ('Super Admin', 'Super Admin')], default='Admin', max_length=50, null=True),
        ),
    ]
