# Generated by Django 4.2.9 on 2025-02-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=11),
            preserve_default=False,
        ),
    ]
