# Generated by Django 5.0.6 on 2025-02-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0003_alter_users_password_alter_users_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='added_by_user_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='users',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='users',
            name='domain_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='domain_user_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_device',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_ip',
        ),
        migrations.RemoveField(
            model_name='users',
            name='plan_type',
        ),
        migrations.RemoveField(
            model_name='users',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
