# Generated by Django 4.2.9 on 2025-02-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0004_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
