# Generated by Django 4.2.9 on 2025-02-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryServices', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='additional_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
