# Generated by Django 5.0.6 on 2025-02-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitems',
            name='additional_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
