# Generated by Django 4.2.9 on 2025-02-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductServices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='addition_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
